TASK: VlspEvjVqaTask

DATASET:
  FEATURE_DATASET:
    TYPE: RawQuestionMultilingualFeatureDataset
    BATCH_SIZE: 15
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: /content/vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: /content/train-images
    SCENE_TEXT_THRESHOLD: 0.3
  DICT_DATASET:
    TYPE: RawQuestionMultilingualDictionaryDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: /content/vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: /content/train-images
    SCENE_TEXT_THRESHOLD: 0.3
  MIN_FREQ: 1
  SCENE_TEXT_THRESHOLD: 0.3
  VOCAB:
    TYPE: VlspVqaMultiModalVocab
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    PRETRAINED_LANGUAGE_MODEL: bert-base-multilingual-uncased
  JSON_PATH:
    TRAIN: /content/drive/MyDrive/VQA/ENVJ_VQA/Data/Data_root/evjvqa_train.json
    DEV: /content/drive/MyDrive/VQA/ENVJ_VQA/Data/Data_root/public-test-data-with-answer/evjvqa_public_test.json
    PUBLIC_TEST: null
    PRIVATE_TEST: null

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 2
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: F1
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 1
  PATIENCE: 5

MODEL:
  ARCHITECTURE: ExtendedMCAN
  NAME: extended_mcan_vlsp
  DEVICE: cuda
  D_MODEL: 512
  DROPOUT: .1
  REGION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: .1
  GRID_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 1024
    D_MODEL: 512
    DROPOUT: .1
  BOX_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 4
    D_MODEL: 512
    DROPOUT: .1
  TEXT_EMBEDDING:
    ARCHITECTURE: BertEmbedding
    PRETRAINED_NAME: bert-base-multilingual-uncased
    D_PRETRAINED_FEATURE: 768
    DEVICE: cuda
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
  SELF_ENCODER:
    ARCHITECTURE: Encoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
  GUIDED_ENCODER:
    ARCHITECTURE: GuidedAttentionEncoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    GUIDED_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
  MULTIMODAL_FUSION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 8
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1
