TASK: OpenEndedTask

DATASET:
  FEATURE_DATASET:
    TYPE: OcrFeatureDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: features/OpenViVQA/features/x152++_faster_rcnn
      SCENE_TEXT: features/OpenViVQA/features/swintextspotter
      IMAGE: null
    SCENE_TEXT_THRESHOLD: 0.3
  DICT_DATASET:
    TYPE: OcrDictionaryDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: features/OpenViVQA/features/x152++_faster_rcnn
      SCENE_TEXT: features/OpenViVQA/features/swintextspotter
      IMAGE: null
    SCENE_TEXT_THRESHOLD: 0.3
  MIN_FREQ: 1
  VOCAB:
    TYPE: OcrVocab
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    OCR_TOKEN: <ocr>
    OCR_DET_TOKEN: <ocr_det>
    OCR_REC_TOKEN: <ocr_rec>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    JSON_PATH:
      TRAIN: features/OpenViVQA/annotations/OpenViVQA_train.json
      DEV: features/OpenViVQA/annotations/OpenViVQA_dev.json
      TEST: features/OpenViVQA/annotations/OpenViVQA_test.json
  JSON_PATH:
    TRAIN: features/OpenViVQA/annotations/OpenViVQA_train.json
    DEV: features/OpenViVQA/annotations/OpenViVQA_dev.json
    TEST: features/OpenViVQA/annotations/OpenViVQA_test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 1.
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 5

MODEL:
  ARCHITECTURE: M4C
  NAME: m4c_x152++_faster_rcnn
  DEVICE: cuda
  D_MODEL: 512
  REGION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 1024
    D_MODEL: 512
    DROPOUT: .1
  GRID_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: .1
  BOX_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 4
    D_MODEL: 512
    DROPOUT: .1
  OCR_DET_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 256
    D_MODEL: 512
    DROPOUT: .1
  OCR_REC_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 256
    D_MODEL: 512
    DROPOUT: .1
  OCR_TEXT_EMBEDDING:
    ARCHITECTURE: OcrEmbedding
    DEVICE: cuda
    OCR_PATH: features/OpenViVQA/features/swintextspotter
    WORD_EMBEDDING: ViFastText
    WORD_EMBEDDING_CACHE: null
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    DEVICE: cuda
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
  DYNAMIC_EMBEDDING:
    ARCHITECTURE: DynamicEmbedding
    DEVICE: cuda
    D_MODEL: 512
    DROPOUT: .1
  ENCODER:
    ARCHITECTURE: MultiModalEncoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
