TASK: MmfClassificationTask

DATASET:
  FEATURE_DATASET:
    TYPE: OcrClassificationDataset
    BATCH_SIZE: 64
    WORKERS: 2
    FEATURE_PATH:
      FEATURES: features/OpenViVQA/features/x152++_faster_rcnn
      SCENE_TEXT: features/OpenViVQA/features/swintextspotter
      IMAGE: null
    SCENE_TEXT_THRESHOLD: 0.3
    MAX_SCENE_TEXT: 50
  VOCAB:
    TYPE: OcrClassificationVocab
    TOKENIZER: null
    SCENE_TEXT_THRESHOLD: 0.3
    MAX_SCENE_TEXT: 50
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    MIN_FREQ: 1
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    OCR_TOKEN: <ocr>
    OCR_DET_TOKEN: <ocr_det>
    OCR_REC_TOKEN: <ocr_rec>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    JSON_PATH:
      TRAIN: features/OpenViVQA/annotations/OpenViVQA_train.json
      DEV: features/OpenViVQA/annotations/OpenViVQA_dev.json
      TEST: features/OpenViVQA/annotations/OpenViVQA_test.json
  JSON_PATH:
    TRAIN: features/OpenViVQA/annotations/OpenViVQA_train.json
    DEV: features/OpenViVQA/annotations/OpenViVQA_dev.json
    TEST: features/OpenViVQA/annotations/OpenViVQA_test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 0.01
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  GET_SCORES: True
  PATIENCE: 5

MODEL:
  ARCHITECTURE: MMF_LoRRA
  NAME: mmf_lorra_x152++_faster_rcnn
  DEVICE: cuda
  D_MODEL: 512
  SCENE_TEXT_THRESHOLD: 0.3
  MAX_SCENE_TEXT: 50
  OBJECT_EMBEDDING:
    D_FEATURE: 1024
    DROPOUT: .1
  BOX_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 4
    D_MODEL: 512
    DROPOUT: .1
  OCR_EMBEDDING:
    D_FEATURE: 300 # (fasttext)
    DROPOUT: .1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    DEVICE: cuda
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null  
  SELF_ATTENTION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 1
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1
  SPATIAL_ATTENTION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 1
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1
  CONTEXT_ATTENTION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 1
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1