task: OpenEndedTask

dataset:
  type: PretrainedOcrDataset
  batch_size: 16
  workers: 0
  feature_path:
    features: data/vinvl_vinvl
    scene_text: data/swintext_spotter
  scene_text_threshold: 0.0
  max_scene_text: 32
  train: data/ViTextVQA_train.json
  dev: data/ViTextVQA_dev.json
  test: data/ViTextVQA_test.json
  vocab:
    type: PretrainedVocab
    pretrained_name: "VietAI/vit5-base"

training:
  checkpoint_path: saved_models
  learning_rate: 1.
  warmup: 10000
  score: Accuracy
  verbose_scores:
    - Accuracy
    - Precision
    - Recall
    - F1
  get_scores: True
  beam_size: 1
  patience: 5

model:
  architecture: SAL
  name: sal_vinvl
  device: mps
  backbone:
    name: "VietAI/vit5-base"
  object_embedding:
    d_feature: 2048
  ocr_embedding:
    d_det: 256
    d_rec: 256
    num_distance: 16