TASK: TrainingHuggingFaceModels

DATASET:
  FEATURE_DATASET:
    TYPE: T5OcrFeatureDataset
    BATCH_SIZE: 16
    WORKERS: 2
    FEATURE_PATH:
      FEATURES: vinvl_vinvl
      SCENE_TEXT: swintext_spotter
      IMAGE: null
    SCENE_TEXT_THRESHOLD: 0.5
    MAX_SCENE_TEXT: 32
    WORD_EMBEDDING: ViFastText
    WORD_EMBEDDING_CACHE: null
  DICT_DATASET:
    TYPE: T5OcrDictionaryDataset
    BATCH_SIZE: 16
    WORKERS: 2
    FEATURE_PATH:
      FEATURES: vinvl_vinvl
      SCENE_TEXT: swintext_spotter
      IMAGE: null
    SCENE_TEXT_THRESHOLD: 0.5
    MAX_SCENE_TEXT: 32
    WORD_EMBEDDING: ViFastText
    WORD_EMBEDDING_CACHE: null
  MIN_FREQ: 1
  VOCAB:
    TYPE: T5OcrVocab
    PRETRAINED_NAME: "VietAI/vit5-base"
    JSON_PATH:
      TRAIN: ViTextVQA_train.json
      DEV: ViTextVQA_dev.json
      TEST: ViTextVQA_test.json
  JSON_PATH:
    TRAIN: ViTextVQA_train.json
    DEV: ViTextVQA_dev.json
    TEST: ViTextVQA_test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 1.
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: Accuracy
  ITER_TO_VERBOSE: 30
  VERBOSE_SCORES:
    - Accuracy
    - Precision
    - Recall
    - F1
  GET_SCORES: True
  TRAINING_BEAM_SIZE: 1
  EVALUATING_BEAM_SIZE: 1
  PATIENCE: 5

MODEL:
  ARCHITECTURE: SAL
  NAME: sal_vinvl
  DEVICE: cuda
  D_MODEL: 512
  BACKBONE:
    NAME: "VietAI/vit5-base"
  EMBEDDING:
    D_MODEL: 512
  OBJECT_EMBEDDING:
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: .1
  BOX_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 4
    D_MODEL: 512
    DROPOUT: .1
  OCR_EMBEDDING:
    D_FEATURE: 512 # 256 (rec_features) + 256 (det_features)
    D_MODEL: 512
    DROPOUT: .1
  TSS:
    DEVICE: cuda
    D_MODEL: 512
  SCP:
    NUM_DISTANCE: 16
    D_MODEL: 512
    HEAD: 8
    D_KEY: 64
    D_VALUE: 64
  ENCODER:
    D_MODEL: 512
    LAYERS: 6
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_KEY: 64
      D_VALUE: 64
      D_MODEL: 512
      USE_AOA: False
      DROPOUT: 0.1
      CAN_BE_STATEFUL: False
    PFF:
      D_MODEL: 512
      D_FF: 2048
      DROPOUT: 0.1
  DECODER:
    TEXT_EMBEDDING: null
    D_MODEL: 512
    LAYERS: 6
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_KEY: 64
      D_VALUE: 64
      D_MODEL: 512
      USE_AOA: False
      DROPOUT: 0.1
      CAN_BE_STATEFUL: True
    PFF:
      D_MODEL: 512
      D_FF: 2048
      DROPOUT: 0.1
    ENC_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_KEY: 64
      D_VALUE: 64
      D_MODEL: 512
      USE_AOA: False
      DROPOUT: 0.1
      CAN_BE_STATEFUL: False
