TASK: VlspEvjVqaTask

DATASET:
  FEATURE_DATASET:
    TYPE: MultilingualFeatureDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: features/EVJVQA/vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: features/EVJVQA/images
    SCENE_TEXT_THRESHOLD: 0.3
  DICT_DATASET:
    TYPE: MultilingualDictionaryDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: features/EVJVQA/vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: features/EVJVQA/images
    SCENE_TEXT_THRESHOLD: 0.3
  MIN_FREQ: 1
  VOCAB:
    TYPE: VlspVqaMultiModalVocab
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    JSON_PATH:
      TRAIN: features/OpenViVQA/annotations/OpenViVQA_train.json
      DEV: features/OpenViVQA/annotations/OpenViVQA_dev.json
      TEST: features/OpenViVQA/annotations/OpenViVQA_test.json
  JSON_PATH:
    TRAIN: features/EVJVQA/annotations/evjvqa_train.json
    DEV: features/EVJVQA/annotations/evjvqa_dev.json
    PUBLIC_TEST: features/EVJVQA/annotations/evjvqa_public_test.json
    PRIVATE_TEST: features/EVJVQA/annotations/evjvqa_private_test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 1
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 5

MODEL:
  ARCHITECTURE: VisiolinguisticTransformer
  NAME: visiolinguistic_transformer_vlsp
  DEVICE: cuda
  REGION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: .1
  GRID_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 1024
    D_MODEL: 512
    DROPOUT: .1
  BOX_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 4
    D_MODEL: 512
    DROPOUT: .1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    DEVICE: cuda
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
  D_MODEL: 512
  DROPOUT: .1
  ENCODER:
    ARCHITECTURE: CoAttentionEncoder
    D_MODEL: 512
    LAYERS: 3
    VISION_LANGUAGE_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    LANGUAGE_VISION_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    VISION_SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    LANGUAGE_SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
  MULTIMODAL_FUSION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 8
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1